import type { Difficulty, Sudoku3DBoard, CellState } from '../types';

// Utility to shuffle an array
function shuffle<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Generate a fully solved 9x9 grid using a mathematical shifting pattern.
// This is O(1) and guaranteed to be valid, avoiding any slow backtracking freezes.
function generateSolved2D(): number[][] {
  const base = [1, 2, 3, 4, 5, 6, 7, 8, 9];
  const grid: number[][] = [];
  
  // Shuffled mapping for number randomization
  const mapping = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]);
  
  for (let r = 0; r < 9; r++) {
    // Standard Sudoku shift pattern to ensure row, col, and box uniqueness
    const shift = 3 * (r % 3) + Math.floor(r / 3);
    const row: number[] = [];
    for (let c = 0; c < 9; c++) {
      const val = base[(c + shift) % 9];
      row.push(mapping[val - 1]);
    }
    grid.push(row);
  }
  
  return grid;
}

/**
 * Generates a 9x9x9 multi-layered Sudoku board.
 * Each layer is generated by shifting the base layer solved configuration.
 */
export function generatePuzzle(difficulty: Difficulty): Sudoku3DBoard {
  const baseGrid = generateSolved2D();
  const board: Sudoku3DBoard = [];

  // Determine how many cells to show per layer (total cells = 81 per layer)
  let cluesPerLayer = 32; // Easy
  if (difficulty === 'medium') cluesPerLayer = 25;
  if (difficulty === 'hard') cluesPerLayer = 18;

  for (let z = 0; z < 9; z++) {
    const layerCells: CellState[][] = [];
    
    // Choose prefilled indices for this layer
    const allIndices = Array.from({ length: 81 }, (_, i) => i);
    const prefilledIndices = new Set(shuffle(allIndices).slice(0, cluesPerLayer));

    for (let y = 0; y < 9; y++) {
      const rowCells: CellState[] = [];
      for (let x = 0; x < 9; x++) {
        // Shift values along Z-axis to maintain 3D Latin Hypercube constraints
        const solvedVal = ((baseGrid[y][x] - 1 + z) % 9) + 1;
        
        const cellIdx = y * 9 + x;
        const show = prefilledIndices.has(cellIdx);

        rowCells.push({
          value: show ? solvedVal : 0,
          isOriginal: show,
          isError: false,
          solvedValue: solvedVal,
          notes: [],
        });
      }
      layerCells.push(rowCells);
    }
    board.push(layerCells);
  }

  return board;
}

/**
 * Checks all cells for rule violations (duplicates along Row, Col, Depth, and 3x3 block).
 * Marks isError = true for violating cells.
 */
export function checkSudokuRules(board: Sudoku3DBoard): Sudoku3DBoard {
  // Create a deep copy of the board to reset errors
  const newBoard: Sudoku3DBoard = board.map((layer) =>
    layer.map((row) =>
      row.map((cell) => ({
        ...cell,
        isError: false,
        notes: [...cell.notes],
      }))
    )
  );

  // Helper to mark coordinate as error
  const markError = (z: number, y: number, x: number) => {
    newBoard[z][y][x].isError = true;
  };

  // 1. Check Row (X-axis) & Col (Y-axis) & 3x3 Box constraints per layer z
  for (let z = 0; z < 9; z++) {
    const layer = newBoard[z];

    // Check Row
    for (let y = 0; y < 9; y++) {
      const counts: { [val: number]: number[] } = {};
      for (let x = 0; x < 9; x++) {
        const val = layer[y][x].value;
        if (val > 0) {
          if (!counts[val]) counts[val] = [];
          counts[val].push(x);
        }
      }
      Object.keys(counts).forEach((valStr) => {
        const indices = counts[parseInt(valStr, 10)];
        if (indices.length > 1) {
          indices.forEach((xIdx) => markError(z, y, xIdx));
        }
      });
    }

    // Check Col
    for (let x = 0; x < 9; x++) {
      const counts: { [val: number]: number[] } = {};
      for (let y = 0; y < 9; y++) {
        const val = layer[y][x].value;
        if (val > 0) {
          if (!counts[val]) counts[val] = [];
          counts[val].push(y);
        }
      }
      Object.keys(counts).forEach((valStr) => {
        const indices = counts[parseInt(valStr, 10)];
        if (indices.length > 1) {
          indices.forEach((yIdx) => markError(z, yIdx, x));
        }
      });
    }

    // Check 3x3 Box
    for (let boxY = 0; boxY < 3; boxY++) {
      for (let boxX = 0; boxX < 3; boxX++) {
        const startY = boxY * 3;
        const startX = boxX * 3;
        const counts: { [val: number]: { y: number; x: number }[] } = {};

        for (let dy = 0; dy < 3; dy++) {
          for (let dx = 0; dx < 3; dx++) {
            const y = startY + dy;
            const x = startX + dx;
            const val = layer[y][x].value;
            if (val > 0) {
              if (!counts[val]) counts[val] = [];
              counts[val].push({ y, x });
            }
          }
        }

        Object.keys(counts).forEach((valStr) => {
          const cells = counts[parseInt(valStr, 10)];
          if (cells.length > 1) {
            cells.forEach((c) => markError(z, c.y, c.x));
          }
        });
      }
    }
  }

  // 2. Check Depth (Z-axis) constraints across layers for each (x, y)
  for (let y = 0; y < 9; y++) {
    for (let x = 0; x < 9; x++) {
      const counts: { [val: number]: number[] } = {};
      for (let z = 0; z < 9; z++) {
        const val = newBoard[z][y][x].value;
        if (val > 0) {
          if (!counts[val]) counts[val] = [];
          counts[val].push(z);
        }
      }
      Object.keys(counts).forEach((valStr) => {
        const layers = counts[parseInt(valStr, 10)];
        if (layers.length > 1) {
          layers.forEach((zIdx) => markError(zIdx, y, x));
        }
      });
    }
  }

  return newBoard;
}

/**
 * Checks if the board has been solved.
 * Wins if all cells are non-zero and no errors exist.
 */
export function checkWinCondition(board: Sudoku3DBoard): boolean {
  for (let z = 0; z < 9; z++) {
    for (let y = 0; y < 9; y++) {
      for (let x = 0; x < 9; x++) {
        const cell = board[z][y][x];
        if (cell.value === 0 || cell.isError) {
          return false;
        }
      }
    }
  }
  return true;
}

/**
 * Identifies all cells that belong to completed, error-free rows, cols, depth lines, or 3x3 boxes.
 */
export function getGlowingCells(board: Sudoku3DBoard): Set<string> {
  const glowing = new Set<string>();

  // Pre-validate rules to ensure we only glow groups that have no errors
  const validatedBoard = checkSudokuRules(board);

  const checkGroup = (coords: { x: number; y: number; z: number }[]) => {
    const hasZero = coords.some((c) => validatedBoard[c.z][c.y][c.x].value === 0);
    const hasError = coords.some((c) => validatedBoard[c.z][c.y][c.x].isError);
    if (!hasZero && !hasError) {
      coords.forEach((c) => glowing.add(`${c.x}-${c.y}-${c.z}`));
    }
  };

  // 1. Check rows, cols, and 3x3 boxes per layer z
  for (let z = 0; z < 9; z++) {
    // Check rows (X-axis)
    for (let y = 0; y < 9; y++) {
      const coords = [];
      for (let x = 0; x < 9; x++) coords.push({ x, y, z });
      checkGroup(coords);
    }
    // Check columns (Y-axis)
    for (let x = 0; x < 9; x++) {
      const coords = [];
      for (let y = 0; y < 9; y++) coords.push({ x, y, z });
      checkGroup(coords);
    }
    // Check 3x3 boxes
    for (let boxY = 0; boxY < 3; boxY++) {
      for (let boxX = 0; boxX < 3; boxX++) {
        const coords = [];
        for (let dy = 0; dy < 3; dy++) {
          for (let dx = 0; dx < 3; dx++) {
            coords.push({ x: boxX * 3 + dx, y: boxY * 3 + dy, z });
          }
        }
        checkGroup(coords);
      }
    }
  }

  // 2. Check depth lines (Z-axis)
  for (let y = 0; y < 9; y++) {
    for (let x = 0; x < 9; x++) {
      const coords = [];
      for (let z = 0; z < 9; z++) coords.push({ x, y, z });
      checkGroup(coords);
    }
  }

  return glowing;
}
