import type { Difficulty, Sudoku3DBoard, CellState } from '../types';

// Utility to shuffle an array
function shuffle<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Generate a fully solved 9x9 grid using a mathematical shifting pattern.
// This is O(1) and guaranteed to be valid, avoiding any slow backtracking freezes.
function generateSolved2D(): number[][] {
  const base = [1, 2, 3, 4, 5, 6, 7, 8, 9];
  const grid: number[][] = [];
  
  // Shuffled mapping for number randomization
  const mapping = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9]);
  
  for (let r = 0; r < 9; r++) {
    // Standard Sudoku shift pattern to ensure row, col, and box uniqueness
    const shift = 3 * (r % 3) + Math.floor(r / 3);
    const row: number[] = [];
    for (let c = 0; c < 9; c++) {
      const val = base[(c + shift) % 9];
      row.push(mapping[val - 1]);
    }
    grid.push(row);
  }
  
  return grid;
}

// Get valid candidates for cell (z, y, x) in a 9x9x9 grid represented as number[][][]
function getCandidates(grid: number[][][], z: number, y: number, x: number): number[] {
  let mask = 0;
  
  // Row constraint (X-axis) in layer z
  for (let col = 0; col < 9; col++) {
    const val = grid[z][y][col];
    if (val > 0) mask |= (1 << val);
  }
  
  // Col constraint (Y-axis) in layer z
  for (let row = 0; row < 9; row++) {
    const val = grid[z][row][x];
    if (val > 0) mask |= (1 << val);
  }
  
  // Box constraint in layer z
  const startRow = Math.floor(y / 3) * 3;
  const startCol = Math.floor(x / 3) * 3;
  for (let r = 0; r < 3; r++) {
    const rIdx = startRow + r;
    for (let c = 0; c < 3; c++) {
      const val = grid[z][rIdx][startCol + c];
      if (val > 0) mask |= (1 << val);
    }
  }
  
  // Depth constraint (Z-axis) across layers
  for (let layer = 0; layer < 9; layer++) {
    const val = grid[layer][y][x];
    if (val > 0) mask |= (1 << val);
  }
  
  const candidates: number[] = [];
  for (let val = 1; val <= 9; val++) {
    if ((mask & (1 << val)) === 0) {
      candidates.push(val);
    }
  }
  return candidates;
}

// Backtracking solver using MRV (Minimum Remaining Values) heuristic
function solve3DBacktrack(
  grid: number[][][],
  emptyCells: { z: number; y: number; x: number }[],
  index: number,
  mode: number
): boolean {
  if (index === emptyCells.length) {
    return true;
  }

  // Find the cell in emptyCells[index...end] with the minimum candidates (MRV)
  let minCandidatesCount = 10;
  let bestIdxInRemaining = -1;
  let bestCandidates: number[] = [];

  for (let i = index; i < emptyCells.length; i++) {
    const { z, y, x } = emptyCells[i];
    const candidates = getCandidates(grid, z, y, x);
    if (candidates.length < minCandidatesCount) {
      minCandidatesCount = candidates.length;
      bestIdxInRemaining = i;
      bestCandidates = candidates;
      if (minCandidatesCount === 0) {
        return false; // Early backtrack
      }
    }
  }

  if (bestIdxInRemaining === -1) {
    return false;
  }

  // Swap emptyCells[index] and emptyCells[bestIdxInRemaining]
  const temp = emptyCells[index];
  emptyCells[index] = emptyCells[bestIdxInRemaining];
  emptyCells[bestIdxInRemaining] = temp;

  const { z, y, x } = emptyCells[index];

  for (const val of bestCandidates) {
    grid[z][y][x] = val;
    if (solve3DBacktrack(grid, emptyCells, index + 1, mode)) {
      return true;
    }
    grid[z][y][x] = 0; // Backtrack
  }

  // Swap back to restore order
  emptyCells[bestIdxInRemaining] = emptyCells[index];
  emptyCells[index] = temp;

  return false;
}

/**
 * Solves a 3D Sudoku board.
 * Mode 0: Normal order (z = 0..8)
 * Mode 1: Odd-Even layers (z = 1, 3, 5, 7, 0, 2, 4, 6, 8)
 * Mode 2: Center-out layers (z = 4, 3, 5, 2, 6, 1, 7, 0, 8)
 * Returns true if solvable, false otherwise.
 */
export function solve3D(grid: number[][][], mode: number = 0): boolean {
  const emptyCells: { z: number; y: number; x: number }[] = [];
  for (let z = 0; z < 9; z++) {
    for (let y = 0; y < 9; y++) {
      for (let x = 0; x < 9; x++) {
        if (grid[z][y][x] === 0) {
          emptyCells.push({ z, y, x });
        }
      }
    }
  }

  if (mode === 1) {
    // Odd then Even layers
    emptyCells.sort((a, b) => {
      const isOddA = a.z % 2 !== 0;
      const isOddB = b.z % 2 !== 0;
      if (isOddA && !isOddB) return -1;
      if (!isOddA && isOddB) return 1;
      return a.z - b.z;
    });
  } else if (mode === 2) {
    // Stride-3 layers (Z order: 0, 3, 6, 1, 4, 7, 2, 5, 8)
    const order = [0, 3, 6, 1, 4, 7, 2, 5, 8];
    emptyCells.sort((a, b) => {
      return order.indexOf(a.z) - order.indexOf(b.z);
    });
  }

  return solve3DBacktrack(grid, emptyCells, 0, mode);
}

/**
 * Generates a 9x9x9 multi-layered Sudoku board.
 * Each layer is generated by shifting the base layer solved configuration.
 */
export function generatePuzzle(difficulty: Difficulty): Sudoku3DBoard {
  // Determine how many cells to show per layer (total cells = 81 per layer)
  let cluesPerLayer = 32; // Easy
  if (difficulty === 'medium') cluesPerLayer = 25;
  if (difficulty === 'hard') cluesPerLayer = 18;

  while (true) {
    const baseGrid = generateSolved2D();
    const board: Sudoku3DBoard = [];

    for (let z = 0; z < 9; z++) {
      const layerCells: CellState[][] = [];
      
      // Choose prefilled indices for this layer
      const allIndices = Array.from({ length: 81 }, (_, i) => i);
      const prefilledIndices = new Set(shuffle(allIndices).slice(0, cluesPerLayer));

      for (let y = 0; y < 9; y++) {
        const rowCells: CellState[] = [];
        for (let x = 0; x < 9; x++) {
          // Shift values along Z-axis to maintain 3D Latin Hypercube constraints
          const solvedVal = ((baseGrid[y][x] - 1 + z) % 9) + 1;
          
          const cellIdx = y * 9 + x;
          const show = prefilledIndices.has(cellIdx);

          rowCells.push({
            value: show ? solvedVal : 0,
            isOriginal: show,
            isError: false,
            solvedValue: solvedVal,
            notes: [],
          });
        }
        layerCells.push(rowCells);
      }
      board.push(layerCells);
    }

    // Validation Layer: Run the solver 3 times to guarantee completion
    let isValid = true;
    for (let run = 0; run < 3; run++) {
      const grid: number[][][] = board.map((layer) =>
        layer.map((row) => row.map((cell) => cell.value))
      );
      if (!solve3D(grid, run)) {
        isValid = false;
        break;
      }
    }

    if (isValid) {
      return board;
    }
  }
}

/**
 * Checks all cells for rule violations (duplicates along Row, Col, Depth, and 3x3 block).
 * Marks isError = true for violating cells.
 */
export function checkSudokuRules(board: Sudoku3DBoard): Sudoku3DBoard {
  // Create a deep copy of the board to reset errors
  const newBoard: Sudoku3DBoard = board.map((layer) =>
    layer.map((row) =>
      row.map((cell) => ({
        ...cell,
        isError: false,
        notes: [...cell.notes],
      }))
    )
  );

  // Helper to mark coordinate as error
  const markError = (z: number, y: number, x: number) => {
    newBoard[z][y][x].isError = true;
  };

  // 1. Check Row (X-axis) & Col (Y-axis) & 3x3 Box constraints per layer z
  for (let z = 0; z < 9; z++) {
    const layer = newBoard[z];

    // Check Row
    for (let y = 0; y < 9; y++) {
      const counts: { [val: number]: number[] } = {};
      for (let x = 0; x < 9; x++) {
        const val = layer[y][x].value;
        if (val > 0) {
          if (!counts[val]) counts[val] = [];
          counts[val].push(x);
        }
      }
      Object.keys(counts).forEach((valStr) => {
        const indices = counts[parseInt(valStr, 10)];
        if (indices.length > 1) {
          indices.forEach((xIdx) => markError(z, y, xIdx));
        }
      });
    }

    // Check Col
    for (let x = 0; x < 9; x++) {
      const counts: { [val: number]: number[] } = {};
      for (let y = 0; y < 9; y++) {
        const val = layer[y][x].value;
        if (val > 0) {
          if (!counts[val]) counts[val] = [];
          counts[val].push(y);
        }
      }
      Object.keys(counts).forEach((valStr) => {
        const indices = counts[parseInt(valStr, 10)];
        if (indices.length > 1) {
          indices.forEach((yIdx) => markError(z, yIdx, x));
        }
      });
    }

    // Check 3x3 Box
    for (let boxY = 0; boxY < 3; boxY++) {
      for (let boxX = 0; boxX < 3; boxX++) {
        const startY = boxY * 3;
        const startX = boxX * 3;
        const counts: { [val: number]: { y: number; x: number }[] } = {};

        for (let dy = 0; dy < 3; dy++) {
          for (let dx = 0; dx < 3; dx++) {
            const y = startY + dy;
            const x = startX + dx;
            const val = layer[y][x].value;
            if (val > 0) {
              if (!counts[val]) counts[val] = [];
              counts[val].push({ y, x });
            }
          }
        }

        Object.keys(counts).forEach((valStr) => {
          const cells = counts[parseInt(valStr, 10)];
          if (cells.length > 1) {
            cells.forEach((c) => markError(z, c.y, c.x));
          }
        });
      }
    }
  }

  // 2. Check Depth (Z-axis) constraints across layers for each (x, y)
  for (let y = 0; y < 9; y++) {
    for (let x = 0; x < 9; x++) {
      const counts: { [val: number]: number[] } = {};
      for (let z = 0; z < 9; z++) {
        const val = newBoard[z][y][x].value;
        if (val > 0) {
          if (!counts[val]) counts[val] = [];
          counts[val].push(z);
        }
      }
      Object.keys(counts).forEach((valStr) => {
        const layers = counts[parseInt(valStr, 10)];
        if (layers.length > 1) {
          layers.forEach((zIdx) => markError(zIdx, y, x));
        }
      });
    }
  }

  return newBoard;
}

/**
 * Checks if the board has been solved.
 * Wins if all cells are non-zero and no errors exist.
 */
export function checkWinCondition(board: Sudoku3DBoard): boolean {
  for (let z = 0; z < 9; z++) {
    for (let y = 0; y < 9; y++) {
      for (let x = 0; x < 9; x++) {
        const cell = board[z][y][x];
        if (cell.value === 0 || cell.isError) {
          return false;
        }
      }
    }
  }
  return true;
}

/**
 * Identifies all cells that belong to completed, error-free rows, cols, depth lines, or 3x3 boxes.
 */
export function getGlowingCells(board: Sudoku3DBoard): Set<string> {
  const glowing = new Set<string>();

  // Pre-validate rules to ensure we only glow groups that have no errors
  const validatedBoard = checkSudokuRules(board);

  const checkGroup = (coords: { x: number; y: number; z: number }[]) => {
    const hasZero = coords.some((c) => validatedBoard[c.z][c.y][c.x].value === 0);
    const hasError = coords.some((c) => validatedBoard[c.z][c.y][c.x].isError);
    if (!hasZero && !hasError) {
      coords.forEach((c) => glowing.add(`${c.x}-${c.y}-${c.z}`));
    }
  };

  // 1. Check rows, cols, and 3x3 boxes per layer z
  for (let z = 0; z < 9; z++) {
    // Check rows (X-axis)
    for (let y = 0; y < 9; y++) {
      const coords = [];
      for (let x = 0; x < 9; x++) coords.push({ x, y, z });
      checkGroup(coords);
    }
    // Check columns (Y-axis)
    for (let x = 0; x < 9; x++) {
      const coords = [];
      for (let y = 0; y < 9; y++) coords.push({ x, y, z });
      checkGroup(coords);
    }
    // Check 3x3 boxes
    for (let boxY = 0; boxY < 3; boxY++) {
      for (let boxX = 0; boxX < 3; boxX++) {
        const coords = [];
        for (let dy = 0; dy < 3; dy++) {
          for (let dx = 0; dx < 3; dx++) {
            coords.push({ x: boxX * 3 + dx, y: boxY * 3 + dy, z });
          }
        }
        checkGroup(coords);
      }
    }
  }

  // 2. Check depth lines (Z-axis)
  for (let y = 0; y < 9; y++) {
    for (let x = 0; x < 9; x++) {
      const coords = [];
      for (let z = 0; z < 9; z++) coords.push({ x, y, z });
      checkGroup(coords);
    }
  }

  return glowing;
}
